---
- name: clone oh-my-zsh
  become: true
  become_user: "{{ item.username }}"
  git:
    repo: "{{ oh-my-zsh-repository }}"
    clone: true
    dest: "~/.oh-my-zsh"
    version: master
  loop: oh-my-zsh-users
  tags:
    - oh-my-zsh
    - installation
