---
- name: install requirements
  import_tasks: requirements.yml
  tags:
    - oh-my-zsh
    - requirements

- name: install oh-my-zsh for each users
  import_tasks: install.yml
  tags:
    - oh-my-zsh
    - installation

- name: download external plugins
  include_tasks: plugins.yml
  loop: "{{ oh_my_zsh_users }}"
  loop_control:
    loop_var: user
    label: user.name
  tags:
    - oh-my-zsh
    - plugins

- name: download theme
  include_tasks: themes.yml
  loop: "{{ oh_my_zsh_users }}"
  loop_control:
    loop_var: user
    label: user.name
  tags:
    - oh-my-zsh
    - themes

- name: configure .zshrc for each users
  import_tasks: zshrc.yml
  tags:
    - oh-my-zsh
    - zshrc
