---
- name: clone plugins
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: "{{ plugin.url }}"
    clone: true
    dest: "$HOME/.oh-my-zsh/custom/plugins/{{ plugin.name }}"
    version: master
  loop: "{{ user.plugins | list }}"
  loop_control:
    loop_var: plugin
    label: "{{ plugin.name }}"
  when: plugin.url is defined
  tags:
    - oh-my-zsh
    - plugins
