---
- name: clone themes
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: "{{ theme.url }}"
    clone: true
    dest: "$HOME/.oh-my-zsh/custom/themes/{{ theme.name }}"
    version: master
  loop: "{{ user.themes | list }}"
  loop_control:
    loop_var: theme
    label: "{{ theme.name }}"
  when: theme.url is defined
  tags:
    - oh-my-zsh
    - themes

- name: create symlink for themes
  become: true
  become_user: "{{ user.name }}"
  file:
    src: "$HOME/.oh-my-zsh/custom/themes/{{ theme.name }}/{{ theme.name }}.zsh-theme"
    dest: "$HOME/.oh-my-zsh/custom/themes/{{ theme.name }}.zsh-theme"
    state: link
  loop: "{{ user.themes | list }}"
  loop_control:
    loop_var: theme
    label: "{{ theme.name }}"
  when: theme.url is defined
  tags:
    - oh-my-zsh
    - themes
