---
- name: copy .zshrc
  become: true
  template:
    dest: "/home/{{ user.name }}/.zshrc"
    src: ./.zshrc.j2
    force: true
    mode: 0644
    backup: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  loop: "{{ oh_my_zsh_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
  tags:
    - oh-my-zsh
    - zshrc
