---
- name: copy .zshrc
  become: true
  become_user: "{{ user.name }}"
  template:
    dest: "{{ user.name }}/.zshrc"
    src: ./zshrc.j2
    force: yes
    mode: 0644
    backup: true
  loop: "{{ oh_my_zsh_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
  tags:
    - oh-my-zsh
    - zshrc
